name: Gerar APK SAMP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Java 8 (Obrigatório para Gradle 4.4)
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Localizar e Dar Permissão
      run: |
        GRADLEW_PATH=$(find . -name gradlew | head -n 1)
        if [ -z "$GRADLEW_PATH" ]; then
          echo "Gerando novo wrapper..."
          gradle wrapper --gradle-version 4.4.1
          chmod +x gradlew
        else
          echo "Encontrado em: $GRADLEW_PATH"
          chmod +x "$GRADLEW_PATH"
        fi

    - name: Compilar APK
      run: |
        GRADLEW_PATH=$(find . -name gradlew | head -n 1)
        # Aceitar licenças do Android SDK automaticamente
        yes | sdkmanager --licenses || true
        $GRADLEW_PATH assembleDebug --stacktrace

    - name: Salvar APK Gerado
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-SAMP-Debug
        path: "**/build/outputs/apk/debug/*.apk"
