name: Gerar APK SAMP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Java 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Localizar e Dar Permissão
      run: |
        GRADLEW_PATH=$(find . -name gradlew)
        if [ -z "$GRADLEW_PATH" ]; then
          echo "Arquivo gradlew não encontrado! Gerando um novo..."
          gradle wrapper --gradle-version 4.4.1
          chmod +x gradlew
        else
          echo "Arquivo encontrado em: $GRADLEW_PATH"
          chmod +x $GRADLEW_PATH
        fi

    - name: Compilar APK
      run: |
        GRADLEW_PATH=$(find . -name gradlew)
        $GRADLEW_PATH assembleDebug --stacktrace

    - name: Salvar APK Gerado
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-SAMP-Debug
        path: "**/build/outputs/apk/debug/*.apk"
